language: java
jdk: oraclejdk7
before_install:
    # Install base Android SDK
    - sudo apt-get update -qq
    - if [ `uname -m` = x86_64 ]; then sudo apt-get install -qq --force-yes libgd2-xpm ia32-libs ia32-libs-multiarch; fi
    - wget http://dl.google.com/android/android-sdk_r22.6-linux.tgz
    - tar xzf android-sdk_r22.6-linux.tgz
    - export ANDROID_HOME=$PWD/android-sdk-linux
    - export PATH=${PATH}:${ANDROID_HOME}/tools:${ANDROID_HOME}/platform-tools

    # Install required Android components.
    - echo y | android update sdk --filter platform-tools,build-tools-19.0.3,sysimg-19,android-19,extra-android-support --no-ui --force

    # Create and start emulator

    # Cant' create android-19 armeabi-v7a avd.
    # Workaround for bug: https://code.google.com/p/android/issues/detail?id=66740
    - rm -rf ${ANDROID_HOME}/system-images/android-19/default/x86

    - echo no | android create avd --force -n test -t android-19
    - emulator -avd test -no-skin -no-audio -no-window &

    # Copy dummy credentials for signing test
    - cp -p ./tests/credentials/* ./.release-credentials/

before_script:
    # Make sure the emulator has started before running tests
    - chmod +x wait-for-emulator
    - ./wait-for-emulator

script:
    - TERM=dumb ./gradlew installDebug
